# -*- coding: utf-8 -*-
"""TablClv2 reg git1 (1).ipynb

Automatically generated by Colab.

Original file is located at
    

## Régression via TabCLv2

Prédiction de revenu futur généré par un joueur dans le contexte des jeux en ligne sur appareil mobile "freemium", où l'enjeu principal pour les éditeurs est d’identifier les utilisateurs à forte valeur ajoutée.

Le modèle cherche à anticiper les revenus futurs générés par un joueur à partir de son comportement initial. La variable cible **$y$** à prédire est le **montant total dépensé** par le joueur sur une période donnée, après l'installation du jeu.

#### Données et Méthodologie
La modélisation porte sur un échantillon de joueurs ayant réalisé au moins un achat durant leur première semaine d'activité. Les variables explicatives utilisées regroupent des données collectées lors des 7 premiers jours:

*   **Indicateurs d'engagement** : nombre de sessions, temps de jeu, score.
*   **Données transactionnelles initiales** : montants et nombre d'achats.
*   **Profil technique et géographique** : système d'exploitation, région, mode d'acquisition.
*   **Évolution du comportement** : tendances de jeu et d'achat.

#### Modèle de prédiction : TabCLv2
Le modèle utilisé est **TabCLv2**, un modèle de fondation pour données tabulaires reposant sur le principe du **In-Context Learning (ICL)**.

Contrairement aux modèles de prédiction classiques qui estiment des poids après une phase d'entraînement spécifique, ce modèle de fondation analyse directement les exemples fournis dans le **"contexte"** pour comprendre les relations statistiques. Cette approche utilise des architectures pré-entraînées, sur des donéées synthétiques, capables de généraliser et de prédire la variable cible instantanément, sans phase d’entraînement supplémentaire.

> **Mise en œuvre :** Le modèle utilise ici un contexte d’observations de joueurs et 16 variables explicatives pour réaliser des prédictions instantanées sur un échantillon test distinct de **5 000 joueurs**.
"""

import torch
import pandas as pd
from tabicl import TabICLRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error

# 1. Détection du processeur de calcul ( CUDA via GPU  si disponible pour accélérer les calculs , cpu sinon)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Utilisation du processeur : {device}")

# 2. Importation  des données
mobiletrain = pd.read_csv("clv_mobile_data_train.txt", sep=r'\s+')
mobiletest = pd.read_csv("clv_mobile_data_test.txt", sep=r'\s+')

#Séparer les caractéristiques (Matrice des features X) de la variable cible (target y) pour les ensembles d'entraînement et de test.

X_train, y_train = mobiletrain.drop(columns=['y']), mobiletrain['y'] # X en maj définit la matrice de l'ensemble des variables explicatives xi
X_test, y_test = mobiletest.drop(columns=['y']), mobiletest['y']

# 3. Déclaration manuelle des variables catégorielles( convertir en  type catégoriel)
namescat = ["country", "difflevel"]
for col in namescat:
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')

# 4. Modèle de régression pré-entrainé  TabICLv2, avec paramètres de base  par défaut pour l'inférence
model = TabICLRegressor(device=device)

print("Calcul in-context avec TabICLv2...")
model.fit(X_train, y_train)

# Apprentissage in-context
preds = model.predict(X_test)

# 5. Afficher les résultats des métriques sur l'échantillon test
print("-" * 45)
print(f"       RÉSULTATS : TabICLv2        ")
print("-" * 45)
print(f"MSE  : {mean_squared_error(y_test, preds):.4f}")
print(f"R²   : {r2_score(y_test, preds):.4f}")
print(f"MAE  : {mean_absolute_error(y_test, preds):.4f}")
print(f"MAPE : {mean_absolute_percentage_error(y_test, preds):.4f}")
print("-" * 45)

"""## Comparaison des Performances : LightGBM vs TabCLV2

Comparaison des résultats du modèle de fondation **TabCLV2** à ceux d'un modèle **LightGBM** optimisé par le TPE Sampler de Optuna( le modèle LightGBM est fait dans un autre notebook) sur le même jeu de données.

### Tableau Comparatif des Métriques

| Métrique | LightGBM (Optimisé Optuna) | TabCLV2 (In-Context Learning) | Amélioration |
| :--- | :---: | :---: | :---: |
| **MSE** (↓) | 23.5593 | **20.9046** | **-11.3%** |
| **R²** (↑) | 0.8448 | **0.8622** | **+2.1%** |
| **MAE** (↓) | 3.7890 | **3.6240** | **-4.4%** |
| **MAPE** (↓) | 0.1369 | **0.1305** | **-4.7%** |

> **Note sur l'optimisation LightGBM :** Les meilleurs paramètres retenus après optimisation étaient : `learning_rate`: 0.034, `n_estimators`: 1656, `num_leaves`: 7, `max_depth`: 8.


Les résultats démontrent que **TabCLV2 surpasse le modèle LightGBM** sur l'ensemble des indicateurs de performance, malgré l'optimisation poussée des hyperparamètres de ce dernier.

Rappel des métriques utilisées pour évaluer la précision des prédictions de Valeur à Vie (CLV) :

*   **MSE (Mean Squared Error - Erreur Quadratique Moyenne)** :  
    Mesure la moyenne des carrés des erreurs (la différence entre la valeur réelle et la prédiction).  
    

*   **R² (Coefficient de Détermination)** :  
    Il représente la proportion de la variance de la variable cible qui est expliquée par le modèle.  
     Il varie de 0 à 1. Un score de **0.86** signifie que le modèle explique **86 %** de la variabilité des dépenses futures des joueurs, ce qui est une excellente performance.

*   **MAE (Mean Absolute Error - Erreur Absolue Moyenne)** :  
    C'est la moyenne des erreurs en valeur absolue.  

*   **MAPE (Mean Absolute Percentage Error - Erreur Moyenne Absolue en Pourcentage)** :  
    Msure l'erreur en pourcentage par rapport aux valeurs réelles.  
     Un MAPE de **0.13** (soit **13 %**) indique qu'en moyenne, l'erreur de prédiction représente 13 % de la valeur réelle dépensée.
"""
